project_id = "lmodeiyrpwvgyqcvjkjr"

[functions.user-service]
verify_jwt = false

[functions.hiring-email-service]
verify_jwt = false

[functions.support-email-service]
verify_jwt = false

[functions.upload-brand-asset]
verify_jwt = false

[functions.analyze-application]
verify_jwt = true

[functions.extract-temperature]
verify_jwt = true

[functions.rescan-temperatures]
verify_jwt = true

[functions.maintenance-service]
verify_jwt = false

[functions.check-alerts]
verify_jwt = false

[functions.send-daily-changelog]
verify_jwt = false

[functions.extract-certification-date]
verify_jwt = true

[functions.parse-catering-order]
verify_jwt = true

[functions.send-push-notification]
verify_jwt = true

[functions.generate-weekly-summary]
verify_jwt = true

[functions.fetch-ovation-scores]
verify_jwt = true

[functions.sales-service]
verify_jwt = false

[functions.trigger-alarm-tasks]
verify_jwt = false

[functions.auto-schedule]
verify_jwt = true

[functions.optimize-labor]
verify_jwt = true

[functions.generate-product-image]
verify_jwt = true

[functions.auto-punch-out]
verify_jwt = false

[functions.sync-pfg-orders]
verify_jwt = false

[functions.labor-service]
verify_jwt = false


[functions.import-bom]
verify_jwt = true

[functions.batch-analyze-applications]
verify_jwt = false

[functions.ai-extraction-service]
verify_jwt = true

[functions.pfg-service]
verify_jwt = false
