-- Add auto punch out time to labor_rules
ALTER TABLE public.labor_rules 
ADD COLUMN IF NOT EXISTS auto_punch_out_time time without time zone;

-- Add flags to time_punches for auto punch out and break violations
ALTER TABLE public.time_punches 
ADD COLUMN IF NOT EXISTS is_auto_punched_out boolean NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS has_break_violation boolean NOT NULL DEFAULT false;

-- Add comment explaining the flags
COMMENT ON COLUMN public.time_punches.is_auto_punched_out IS 'True if this clock_out was auto-generated by the system';
COMMENT ON COLUMN public.time_punches.has_break_violation IS 'True if shift exceeds break threshold without required break';
COMMENT ON COLUMN public.labor_rules.auto_punch_out_time IS 'Time at which employees are automatically clocked out if still punched in';